# yaml-language-server: $schema=https://json.schemastore.org/stylelintrc.json
# explicitly setting schema since using non-standard filename
#───────────────────────────────────────────────────────────────────────────────
# DOCS https://stylelint.io/user-guide/rules
#───────────────────────────────────────────────────────────────────────────────
reportInvalidScopeDisables: true
reportNeedlessDisables: true
#───────────────────────────────────────────────────────────────────────────────
# INFO auto-fixed rules are declared as warnings, so they are not displayed in
# the editor due to `--quiet`
defaultSeverity: warning
#───────────────────────────────────────────────────────────────────────────────
rules:
  annotation-no-unknown: true
  at-rule-no-unknown: true
  block-no-empty: true
  color-no-invalid-hex: true
  comment-no-empty: true
  custom-property-no-missing-var-function: true
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-duplicate-properties:
    - true
    - ignore:
        - consecutive-duplicates-with-different-syntaxes
  declaration-block-no-shorthand-property-overrides: true
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  function-no-unknown: true
  keyframe-block-no-duplicate-selectors: true
  keyframe-declaration-no-important: true
  media-feature-name-no-unknown: true
  media-query-no-invalid: true
  named-grid-areas-no-invalid: true
  no-descending-specificity: [true, {ignore: [selectors-within-list]}]
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-invalid-double-slash-comments: true
  no-invalid-position-at-import-rule: true
  no-irregular-whitespace: true
  property-no-unknown: true
  selector-anb-no-unmatchable: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
  string-no-newline: true
  unit-no-unknown: true
  alpha-value-notation:
    - percentage
    - exceptProperties:
        - opacity
        - fill-opacity
        - flood-opacity
        - stop-opacity
        - stroke-opacity
  at-rule-empty-line-before:
    - always
    - except:
        - blockless-after-same-name-blockless
        - first-nested
      ignore:
        - after-comment
  at-rule-no-vendor-prefix: true
  color-function-notation: [modern, {ignore: [with-var-inside]}]
  color-hex-length: short
  comment-empty-line-before: null
  comment-whitespace-inside: always
  custom-property-empty-line-before: never
  custom-media-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - {}
  custom-property-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - {}
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-single-line-max-declarations: 1
  declaration-empty-line-before: never
  font-family-name-quotes: always-where-recommended
  function-name-case: lower
  function-url-quotes: always
  hue-degree-notation: number # compatible with ccc.nvim output
  import-notation: url
  keyframe-selector-notation: percentage-unless-within-keyword-only-block
  keyframes-name-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - {}
  length-zero-no-unit:
    - true
    - ignore:
        - custom-properties
  media-feature-name-no-vendor-prefix: true
  media-feature-range-notation: context
  number-max-precision: 4
  property-no-vendor-prefix: true
  rule-empty-line-before:
    - always-multi-line
    - except:
        - first-nested
      ignore:
        - after-comment
  selector-attribute-quotes: always
  selector-class-pattern: null # class names usually not defined by me
  selector-id-pattern:
    - ^([a-z][a-z0-9]*)(-[a-z0-9]+)*$
    - {}
  selector-no-vendor-prefix: true
  selector-not-notation: complex
  selector-pseudo-element-colon-notation: double
  selector-type-case: lower
  shorthand-property-no-redundant-values: true
  value-keyword-case: lower
  value-no-vendor-prefix:
    - true
    - ignoreValues:
        - box
        - inline-box
  color-named: never
  color-no-hex: true
  declaration-no-important: true
  font-weight-notation: numeric
  max-nesting-depth: 3
  no-unknown-custom-properties: [true, {severity: error}] # equivalent to "no undeclared variables" in other linters
  selector-nested-pattern: ["&", {splitList: true, message: "Nested selectors should include a &."}]
