name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
  - type: input
    id: obsi-version
    attributes:
      label: Obsidian Version
      description: You can find the version in the *About* Tab of the settings.
      placeholder: 0.13.19
    validations:
      required: true
  - type: input
    id: installer-version
    attributes:
      label: Installer Version
      description: You can find the version in the *About* Tab of the settings.
      placeholder: 0.13.19
    validations:
      required: true
  - type: checkboxes
    id: editor
    attributes:
      label: Which editor are you using?
      description: If you are using the Legacy Editor, please be aware that new features for the theme are mostly only implemented for the new editor, so it is not a bug when they are missing.
      options:
        - label: New Editor
        - label: Legacy Editor
  - type: checkboxes
    id: mode
    attributes:
      label: In which mode(s) does the problem occur? (if applicable)
      options:
        - label: Source (Edit)
        - label: Reading (Preview)
        - label: Live Preview
  - type: checkboxes
    id: operating-system
    attributes:
      label: Which operating system?
      options:
        - label: macOS
        - label: Linux
        - label: Windows
        - label: iOS
        - label: Android
  - type: checkboxes
    id: plugin-specific
    attributes:
      label: Plugin-Specific Problems
      description: |
        Regarding one of these plugin:
        - Longform
        - Kanban
        - Sliding Panes
        - Breadcrumbs
        - Quick Explorer
        - Dataview
        - Ozan's Image in Editor
        - Starred (Core Plugin)
        - Recent Files
      options:
        - label: I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
          required: true
        - label: I made sure that the issue is related to this theme, by checking that the problem does not occur with other themes or the default theme.
          required: true
        - label: In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
          required: true
        - label: If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a Style Setting to turn if off again.)
          required: true

