name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: Add screenshots or a screen recording to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
    validations:
      required: true
  - type: input
    id: obsi-version
    attributes:
      label: Obsidian Version
      description: You can find the version in the *About* Tab of the Obsidian settings.
      placeholder: "0.16.19"
    validations:
      required: true
  - type: input
    id: installer-version
    attributes:
      label: Installer Version
      description: You can find the installer version in the *About* tab of the Obsidian settings.
      placeholder: "0.13.19"
    validations:
      required: true
  - type: checkboxes
    id: mode
    attributes:
      label: In which mode(s) does the problem occur? (if applicable)
      options:
        - label: Source (Edit)
        - label: Reading (Preview)
        - label: Live Preview
  - type: checkboxes
    id: operating-system
    attributes:
      label: Which operating system?
      options:
        - label: macOS
        - label: Linux
        - label: Windows
        - label: iOS
        - label: Android
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
          required: true
        - label: If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)
          required: true
        - label: I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
          required: true
        - label: In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
          required: true
        - label: My issue concerns Obsidian version 0.16+ and I am not using the Legacy Editor. (Older Obsidian versions and the Lecacy Editor are not supported anymore.)
          required: true

