name: Contribution
description: Suggest a CSS snippet for the theme
title: "Contribution: "
labels: ["contribution"]
body:
  - type: markdown
    attributes:
      value: |
        First of all, thank you for making a contribution! Please note that due to compatibility reasons and the specific design vision of the theme, not all contributions will be added.
  - type: dropdown
    id: contribution-type
    attributes:
      label: Type of Contribution
      options:
        - Theme Improvement
        - Support for a plugin
        - Feature Request implementation
        - Bug Fix
        - Color Scheme
        - Other
    validations:
      required: true
  - type: textarea
    id: feature-requested
    attributes:
      label: Description
      description: |
        Briefly describe what the contributed CSS does.
        - If you are fixing an issue, include the issue number.
        - If you are adding support for a plugin, add a link to the plugin.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: If applicable, add screenshots or a screen recording what the contribution does.

