name: Feature request
description: Suggest an idea
title: "Feature request: "
labels: ["feature request"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label:
            I updated to the latest version of the theme (`Settings` → `Appearance` → `Check for
            updates`).
          required: true
        - label:
            The feature would be useful to more users than just me. (If it's only relevant to you,
            have you considered using a [CSS
            snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)
          required: true
        - label:
            The request is about Obsidian desktop, Obsidian mobile is not supported by this theme.
          required: true
  - type: textarea
    id: feature-requested
    attributes:
      label: Feature requested
      description: A clear and concise description of the feature.
    validations: { required: true }
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant screenshot
      description: If applicable, add screenshots or a screen recording to help explain the request.
